In [2]:
'''Retrieve all inputs executed in the current kernel section'''
%history

# Inner dimensions must match:

print((2, 3) @ (3, 2))
print((3, 2) @ (2, 3))
'''Retrieve all inputs executed in the current kernel section'''
%history


### Starting notebook

In [1]:
import torch

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import warnings

In [2]:
print('Pytorch version: ', torch.__version__)
print('Pandas version: ', pd.__version__)
print('Numpy version: ', np.__version__)

Pytorch version:  2.3.1+cpu
Pandas version:  2.2.2
Numpy version:  2.1.0


### Tensors

In [5]:
# Scalar
scalar = torch.tensor(7)
print('Número de dimensões: ', scalar.ndim)
print('Shape: ', scalar.shape)
print('')
print(scalar)

Número de dimensões:  0
Shape:  torch.Size([])

tensor(7)


In [6]:
# Vector
vector = torch.tensor([7, 7])
print('Número de dimensões: ', vector.ndim)
print('Shape: ', vector.shape)
print('')
print(vector)

Número de dimensões:  1
Shape:  torch.Size([2])

tensor([7, 7])


In [7]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
print('Número de dimensões: ', MATRIX.ndim)
print('Shape: ', MATRIX.shape)
print('')
print(MATRIX)

Número de dimensões:  2
Shape:  torch.Size([2, 2])

tensor([[ 7,  8],
        [ 9, 10]])


In [8]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
print('Número de dimensões: ', TENSOR.ndim)
print('Shape: ', TENSOR.shape)
print('')
print(TENSOR)

Número de dimensões:  3
Shape:  torch.Size([1, 3, 3])

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])


### Random tensors

In [9]:
#Also random tensors

rand = torch.rand(2)
print('Número de dimensões: ', rand.ndim)
print(rand)

print('')

rand = torch.rand(2,2)
print('Número de dimensões: ', rand.ndim)
print(rand)

print('')

rand = torch.rand(2,2,2)
print('Número de dimensões: ', rand.ndim)
print(rand)

Número de dimensões:  1
tensor([0.1513, 0.6563])

Número de dimensões:  2
tensor([[0.2659, 0.9191],
        [0.2692, 0.1717]])

Número de dimensões:  3
tensor([[[0.9919, 0.5125],
         [0.3751, 0.5561]],

        [[0.0355, 0.4951],
         [0.1802, 0.8330]]])


In [10]:
# Create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, colour channels (R, G, B)

print('Número de dimensões: ', random_image_size_tensor.ndim)
print('Shape: ', random_image_size_tensor.shape)
print('')
#print(random_image_size_tensor)

Número de dimensões:  3
Shape:  torch.Size([3, 224, 224])



### Zeros, ones and range

In [11]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
print('Número de dimensões: ', zeros.ndim)
print('Shape: ', zeros.shape)
print('')
print(zeros)

Número de dimensões:  2
Shape:  torch.Size([3, 4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [12]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
print('Número de dimensões: ', ones.ndim)
print('Shape: ', ones.shape)
print('')
print(ones)  

Número de dimensões:  2
Shape:  torch.Size([3, 4])

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [13]:
# Create a tensor with a range
one_to_ten = torch.arange(start=1, end=11, step=1)
print('Número de dimensões: ', one_to_ten.ndim)
print('Shape: ', one_to_ten.shape)
print('')
print(one_to_ten)   

Número de dimensões:  1
Shape:  torch.Size([10])

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [14]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
print('Número de dimensões: ', ten_zeros.ndim)
print('Shape: ', ten_zeros.shape)
print('')
print(ten_zeros)   

Número de dimensões:  1
Shape:  torch.Size([10])

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


### Tensor datatypes

In [15]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

print('Dimensões: ', float_32_tensor.ndim)
print('Shape:     ', float_32_tensor.shape)
print('Type:      ', float_32_tensor.dtype)
print('Device:    ', float_32_tensor.device)
print('')
print(float_32_tensor)   

Dimensões:  1
Shape:      torch.Size([3])
Type:       torch.float32
Device:     cpu

tensor([3., 6., 9.])


In [16]:
# Tensor with type float16
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)
print('Type: ', float_16_tensor.dtype)

Type:  torch.float16


In [17]:
# Tensor with type float16
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.half)
print('Type: ', float_16_tensor.dtype)

Type:  torch.float16


In [18]:
# Tensor with type 8-bit
int_8_tensor = torch.tensor([3, 6, 9],
                               dtype=torch.int8)
print('Type: ', int_8_tensor.dtype)

Type:  torch.int8


### Tensor operations

In [19]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor += 10
print(tensor)

tensor([11, 12, 13])


In [20]:
# Substract tensor by 10 
tensor = torch.tensor([1, 2, 3])
tensor -= 10
print(tensor)

tensor([-9, -8, -7])


In [21]:
# Multiply tensor by 10
tensor = torch.tensor([1, 2, 3])
tensor *= 10
print(tensor)

tensor([10, 20, 30])


In [22]:
# Divide tensor by 10
tensor = torch.tensor([1., 2., 3.])
tensor *= 0.1
print(tensor)

tensor([0.1000, 0.2000, 0.3000])


In [23]:
# Try out PyTorch in-built functions
tensor = torch.tensor([1, 2, 3])
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix multiplication

In [59]:
# Inner dimensions must match:

tensor1 = torch.randn(3)
tensor2 = torch.randn(3)

print('Tensor1 shape: ', tensor1.shape)
print('Tensor2 shape: ', tensor2.shape)
print()
print('Resulting tensor: ', torch.matmul(tensor1, tensor2))
print('Resulting shape: ', torch.matmul(tensor1, tensor2).shape)

Tensor1 shape:  torch.Size([3])
Tensor2 shape:  torch.Size([3])

Resulting tensor:  tensor(-1.9401)
Resulting shape:  torch.Size([])


In [63]:
# Another way
print('Resulting tensor: ', tensor1 @ tensor2)

Resulting tensor:  tensor([[ 0.1686,  2.1511,  1.6121],
        [ 0.7154,  1.8139, -2.1160],
        [-0.2792, -0.6681,  0.4708]])


In [62]:
# Inner dimensions must match:

tensor1 = torch.randn(3,3)
tensor2 = torch.randn(3,3)

print('Tensor1 shape: ', tensor1.shape)
print('Tensor2 shape: ', tensor2.shape)
print()
print('Resulting tensor: ', torch.matmul(tensor1, tensor2))
print()
print('Resulting shape: ', torch.matmul(tensor1, tensor2).shape)

Tensor1 shape:  torch.Size([3, 3])
Tensor2 shape:  torch.Size([3, 3])

Resulting tensor:  tensor([[ 0.1686,  2.1511,  1.6121],
        [ 0.7154,  1.8139, -2.1160],
        [-0.2792, -0.6681,  0.4708]])

Resulting shape:  torch.Size([3, 3])


In [61]:
# Inner dimensions must match:

tensor1 = torch.randn(2,2,2)
tensor2 = torch.randn(2,2,2)

print('Tensor1 shape: ', tensor1.shape)
print('Tensor2 shape: ', tensor2.shape)
print()
print('Resulting tensor: ', torch.matmul(tensor1, tensor2))
print()
print('Resulting shape: ', torch.matmul(tensor1, tensor2).shape)

Tensor1 shape:  torch.Size([2, 2, 2])
Tensor2 shape:  torch.Size([2, 2, 2])

Resulting tensor:  tensor([[[-3.1993,  0.3359],
         [-5.3388, -0.2914]],

        [[ 1.7765,  0.1580],
         [ 0.6964, -0.1051]]])

Resulting shape:  torch.Size([2, 2, 2])


In [64]:
# Also, element-wise multiplication:

tensor1 = torch.randn(3)
tensor2 = torch.randn(3)

print('Tensor1 shape: ', tensor1.shape)
print('Tensor2 shape: ', tensor2.shape)
print()
print('Resulting tensor: ', tensor1 * tensor2)
print('Resulting shape: ', (tensor1 * tensor2).shape)

Tensor1 shape:  torch.Size([3])
Tensor2 shape:  torch.Size([3])

Resulting tensor:  tensor([-0.0755, -1.8318,  1.1054])
Resulting shape:  torch.Size([3])


In [68]:
# We can transpose tensors to match their dimensions

tensor1 = torch.randn(3,2)
tensor2 = torch.randn(3,2)

tensor2 = torch.transpose(tensor2,0,1)

print('Tensor1 shape: ', tensor1.shape)
print('Tensor2 shape: ', tensor2.shape)
print()
print('Resulting tensor: ', torch.matmul(tensor1, tensor2))
print()
print('Resulting shape: ', torch.matmul(tensor1, tensor2).shape)

Tensor1 shape:  torch.Size([3, 2])
Tensor2 shape:  torch.Size([2, 3])

Resulting tensor:  tensor([[-0.4450,  0.7958,  0.1773],
        [ 1.0950, -0.7245, -0.1784],
        [-0.0659, -1.1515, -0.2391]])

Resulting shape:  torch.Size([3, 3])


In [70]:
# Also 


tensor1 = torch.randn(3,2)
tensor2 = torch.randn(3,2)

print('Tensor1 shape: ', tensor1.shape)
print('Tensor2 shape: ', tensor2.shape)
print()
print('Resulting tensor: ', torch.matmul(tensor1, tensor2.T))
print()
print('Resulting shape: ', torch.matmul(tensor1, tensor2.T).shape)

Tensor1 shape:  torch.Size([3, 2])
Tensor2 shape:  torch.Size([3, 2])

Resulting tensor:  tensor([[-0.5426, -1.1066,  1.1268],
        [ 0.7317,  0.2338, -0.3682],
        [ 4.8520, -0.6241, -0.4516]])

Resulting shape:  torch.Size([3, 3])


In [75]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)

# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 

x = tensor1
output = linear(x)

print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[ 1.0246,  0.0043,  0.2204, -0.3602,  1.0342,  0.6352],
        [ 0.4047,  0.3082,  0.4408,  0.1429,  0.1551, -0.1431],
        [ 0.7088,  1.6588,  0.8948,  1.3228, -1.5753, -0.7285]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


### Finding the min, max, mean, sum, etc (aggregation)

In [77]:
# Create a tensor
x = torch.arange(0, 100, 10)
print(x)

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])


In [78]:
# let's perform some aggregation

print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [79]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


### Change tensor datatype

In [80]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [81]:
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [89]:
# Change tensor type:
tensor_float16.type(dtype=torch.float32)

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [82]:
# Create a int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [91]:
# Change tensor type:
tensor_int8.type(dtype=torch.float32)

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.])

### Reshaping, stacking, squeezing and unsqueezing

In [92]:
# Create a tensor
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [93]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [94]:
# Change view (keeps same data as original but changes view)
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [95]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [96]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [97]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [98]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [99]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Indexing

In [4]:
# Create a tensor 
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

OSError: [WinError 126] Não foi possível encontrar o módulo especificado. Error loading "C:\Users\Nathan Ferig\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.