### Starting notebook

In [5]:
import torch

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import warnings

In [6]:
print('Pytorch version: ', torch.__version__)
print('Pandas version: ', pd.__version__)
print('Numpy version: ', np.__version__)

Pytorch version:  2.4.0+cu121
Pandas version:  2.1.4
Numpy version:  1.26.4


### Tensors

In [7]:
# Scalar
scalar = torch.tensor(7)
print('Número de dimensões: ', scalar.ndim)
print('Shape: ', scalar.shape)
print('')
print(scalar)

Número de dimensões:  0
Shape:  torch.Size([])

tensor(7)


In [8]:
# Vector
vector = torch.tensor([7, 7])
print('Número de dimensões: ', vector.ndim)
print('Shape: ', vector.shape)
print('')
print(vector)

Número de dimensões:  1
Shape:  torch.Size([2])

tensor([7, 7])


In [9]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
print('Número de dimensões: ', MATRIX.ndim)
print('Shape: ', MATRIX.shape)
print('')
print(MATRIX)

Número de dimensões:  2
Shape:  torch.Size([2, 2])

tensor([[ 7,  8],
        [ 9, 10]])


In [10]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
print('Número de dimensões: ', TENSOR.ndim)
print('Shape: ', TENSOR.shape)
print('')
print(TENSOR)

Número de dimensões:  3
Shape:  torch.Size([1, 3, 3])

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])


### Random tensors

In [11]:
#Also random tensors

rand = torch.rand(2)
print('Número de dimensões: ', rand.ndim)
print(rand)

print('')

rand = torch.rand(2,2)
print('Número de dimensões: ', rand.ndim)
print(rand)

print('')

rand = torch.rand(2,2,2)
print('Número de dimensões: ', rand.ndim)
print(rand)

Número de dimensões:  1
tensor([0.1137, 0.9212])

Número de dimensões:  2
tensor([[0.2834, 0.9582],
        [0.6202, 0.9679]])

Número de dimensões:  3
tensor([[[0.8830, 0.5781],
         [0.8220, 0.8980]],

        [[0.0940, 0.7943],
         [0.3740, 0.9221]]])


In [12]:
# Create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, colour channels (R, G, B)

print('Número de dimensões: ', random_image_size_tensor.ndim)
print('Shape: ', random_image_size_tensor.shape)
print('')
#print(random_image_size_tensor)

Número de dimensões:  3
Shape:  torch.Size([3, 224, 224])



### Zeros, ones and range

In [13]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
print('Número de dimensões: ', zeros.ndim)
print('Shape: ', zeros.shape)
print('')
print(zeros)

Número de dimensões:  2
Shape:  torch.Size([3, 4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [14]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
print('Número de dimensões: ', ones.ndim)
print('Shape: ', ones.shape)
print('')
print(ones)

Número de dimensões:  2
Shape:  torch.Size([3, 4])

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [15]:
# Create a tensor with a range
one_to_ten = torch.arange(start=1, end=11, step=1)
print('Número de dimensões: ', one_to_ten.ndim)
print('Shape: ', one_to_ten.shape)
print('')
print(one_to_ten)

Número de dimensões:  1
Shape:  torch.Size([10])

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [16]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
print('Número de dimensões: ', ten_zeros.ndim)
print('Shape: ', ten_zeros.shape)
print('')
print(ten_zeros)

Número de dimensões:  1
Shape:  torch.Size([10])

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


### Tensor datatypes

In [17]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

print('Dimensões: ', float_32_tensor.ndim)
print('Shape:     ', float_32_tensor.shape)
print('Type:      ', float_32_tensor.dtype)
print('Device:    ', float_32_tensor.device)
print('')
print(float_32_tensor)

Dimensões:  1
Shape:      torch.Size([3])
Type:       torch.float32
Device:     cpu

tensor([3., 6., 9.])


In [18]:
# Tensor with type float16
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)
print('Type: ', float_16_tensor.dtype)

Type:  torch.float16


In [19]:
# Tensor with type float16
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.half)
print('Type: ', float_16_tensor.dtype)

Type:  torch.float16


In [20]:
# Tensor with type 8-bit
int_8_tensor = torch.tensor([3, 6, 9],
                               dtype=torch.int8)
print('Type: ', int_8_tensor.dtype)

Type:  torch.int8


### Tensor operations

In [21]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor += 10
print(tensor)

tensor([11, 12, 13])


In [22]:
# Substract tensor by 10
tensor = torch.tensor([1, 2, 3])
tensor -= 10
print(tensor)

tensor([-9, -8, -7])


In [23]:
# Multiply tensor by 10
tensor = torch.tensor([1, 2, 3])
tensor *= 10
print(tensor)

tensor([10, 20, 30])


In [24]:
# Divide tensor by 10
tensor = torch.tensor([1., 2., 3.])
tensor *= 0.1
print(tensor)

tensor([0.1000, 0.2000, 0.3000])


In [25]:
# Try out PyTorch in-built functions
tensor = torch.tensor([1, 2, 3])
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix multiplication

In [26]:
# Inner dimensions must match:

tensor1 = torch.randn(3)
tensor2 = torch.randn(3)

print('Tensor1 shape: ', tensor1.shape)
print('Tensor2 shape: ', tensor2.shape)
print()
print('Resulting tensor: ', torch.matmul(tensor1, tensor2))
print('Resulting shape: ', torch.matmul(tensor1, tensor2).shape)

Tensor1 shape:  torch.Size([3])
Tensor2 shape:  torch.Size([3])

Resulting tensor:  tensor(-0.4245)
Resulting shape:  torch.Size([])


In [27]:
# Another way
print('Resulting tensor: ', tensor1 @ tensor2)

Resulting tensor:  tensor(-0.4245)


In [28]:
# Inner dimensions must match:

tensor1 = torch.randn(3,3)
tensor2 = torch.randn(3,3)

print('Tensor1 shape: ', tensor1.shape)
print('Tensor2 shape: ', tensor2.shape)
print()
print('Resulting tensor: ', torch.matmul(tensor1, tensor2))
print()
print('Resulting shape: ', torch.matmul(tensor1, tensor2).shape)

Tensor1 shape:  torch.Size([3, 3])
Tensor2 shape:  torch.Size([3, 3])

Resulting tensor:  tensor([[-0.5677,  0.5790, -0.1779],
        [ 1.5793, -0.5869, -0.1894],
        [-0.3714, -1.6159,  1.3086]])

Resulting shape:  torch.Size([3, 3])


In [29]:
# Inner dimensions must match:

tensor1 = torch.randn(2,2,2)
tensor2 = torch.randn(2,2,2)

print('Tensor1 shape: ', tensor1.shape)
print('Tensor2 shape: ', tensor2.shape)
print()
print('Resulting tensor: ', torch.matmul(tensor1, tensor2))
print()
print('Resulting shape: ', torch.matmul(tensor1, tensor2).shape)

Tensor1 shape:  torch.Size([2, 2, 2])
Tensor2 shape:  torch.Size([2, 2, 2])

Resulting tensor:  tensor([[[ 0.9982, -0.5291],
         [ 1.2354, -0.7374]],

        [[ 4.6505, -1.0295],
         [ 2.3554, -2.4252]]])

Resulting shape:  torch.Size([2, 2, 2])


In [30]:
# Also, element-wise multiplication:

tensor1 = torch.randn(3)
tensor2 = torch.randn(3)

print('Tensor1 shape: ', tensor1.shape)
print('Tensor2 shape: ', tensor2.shape)
print()
print('Resulting tensor: ', tensor1 * tensor2)
print('Resulting shape: ', (tensor1 * tensor2).shape)

Tensor1 shape:  torch.Size([3])
Tensor2 shape:  torch.Size([3])

Resulting tensor:  tensor([ 1.4134, -1.0557, -0.0426])
Resulting shape:  torch.Size([3])


In [31]:
# We can transpose tensors to match their dimensions

tensor1 = torch.randn(3,2)
tensor2 = torch.randn(3,2)

tensor2 = torch.transpose(tensor2,0,1)

print('Tensor1 shape: ', tensor1.shape)
print('Tensor2 shape: ', tensor2.shape)
print()
print('Resulting tensor: ', torch.matmul(tensor1, tensor2))
print()
print('Resulting shape: ', torch.matmul(tensor1, tensor2).shape)

Tensor1 shape:  torch.Size([3, 2])
Tensor2 shape:  torch.Size([2, 3])

Resulting tensor:  tensor([[ 3.6869,  1.9689,  5.5447],
        [-0.4775,  0.1570, -1.5350],
        [ 0.0547,  0.1324, -0.1224]])

Resulting shape:  torch.Size([3, 3])


In [32]:
# Also


tensor1 = torch.randn(3,2)
tensor2 = torch.randn(3,2)

print('Tensor1 shape: ', tensor1.shape)
print('Tensor2 shape: ', tensor2.shape)
print()
print('Resulting tensor: ', torch.matmul(tensor1, tensor2.T))
print()
print('Resulting shape: ', torch.matmul(tensor1, tensor2.T).shape)

Tensor1 shape:  torch.Size([3, 2])
Tensor2 shape:  torch.Size([3, 2])

Resulting tensor:  tensor([[ 2.3069,  2.3741, -1.7873],
        [ 1.6559,  1.6928, -1.2878],
        [-1.1366, -1.1877,  0.8727]])

Resulting shape:  torch.Size([3, 3])


In [33]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)

# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value

x = tensor1
output = linear(x)

print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[ 0.1443, -0.9476,  0.0148, -0.9618,  1.7800,  0.4222],
        [ 0.3119, -0.6343,  0.1035, -0.7217,  1.4477,  0.3776],
        [ 0.8055,  0.6398,  0.4963,  0.3199, -0.0376,  0.0196]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


### Finding the min, max, mean, sum, etc (aggregation)

In [34]:
# Create a tensor
x = torch.arange(0, 100, 10)
print(x)

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])


In [35]:
# let's perform some aggregation

print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [36]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


### Change tensor datatype

In [37]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [38]:
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [39]:
# Change tensor type:
tensor_float16.type(dtype=torch.float32)

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [40]:
# Create a int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [41]:
# Change tensor type:
tensor_int8.type(dtype=torch.float32)

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.])

### Reshaping, stacking, squeezing and unsqueezing

In [42]:
# Create a tensor
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [43]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [44]:
# Change view (keeps same data as original but changes view)
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [45]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [46]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [47]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [48]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [49]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Indexing
Select specific data from tensors

In [50]:
# Create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [51]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [52]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

# PyTorch tensors & NumPy

In [53]:
# NumPy array to tensor
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [54]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [55]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducibility

In [56]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")

print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.8016, 0.3649, 0.6286, 0.9663],
        [0.7687, 0.4566, 0.5745, 0.9200],
        [0.3230, 0.8613, 0.0919, 0.3102]])

Tensor B:
tensor([[0.9536, 0.6002, 0.0351, 0.6826],
        [0.3743, 0.5220, 0.1336, 0.9666],
        [0.9754, 0.8474, 0.8988, 0.1105]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [57]:
# # Set the random seed
RANDOM_SEED=42

torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
torch.random.manual_seed(seed=RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")

print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

# Running tensors on GPUs

In [58]:
# Check for GPU Running Locally
import torch
torch.cuda.is_available()

True

In [59]:
# Count number of devices
torch.cuda.device_count()

1

In [60]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [61]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [62]:
# Copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])